= Справочник событий уведомлений

Справочник не имеет интерфейса. Когда возникает определенное событие, например, завершается задание на согласование, требуется отправка уведомлений по нему. В карточке настроек уведомления имеется возможность настроить то, какие уведомления рассылать, кому, куда.

В данный момент справочник можно заполнять кодом расширений сервиса уведомлений или через интерфейс DVExplorer.

== Карточка настроек уведомлений

В карточке настроек уведомления указывается следующая информация:

* Название карточки.
* Описание карточки.
* Тему уведомления.
//  (позже сделаем поддержку XSLT-преобразований):
* Текст уведомления.
// (позже сделаем поддержку XSLT-преобразований):
* Получателей уведомления из справочника сотрудников.
// (позже сделаем поддержку XSLT-преобразований).
Среди получателей могут быть выбраны сотрудники, организации/подразделения, роли, группы, контрагенты.

* Канал уведомления из списка полученного из xref:settings-directory.adoc[Справочника настроек] сервиса уведомлений.
// , в начале будет доступен только вариант с электронной почтой:
* Какие вложения прикреплять к уведомлению.
* Основные файлы.
* Дополнительные файлы.

== Карточка настроек рассылки уведомлений

В карточке настроек рассылки уведомлений указывается:

* Название карточки.
* Событие из справочника событий.
* Ссылки на созданные карточки настроек уведомления.
