= Общие сведения о модуле

{ns} предназначен для отправки уведомлений пользователям о событиях в системе {dv}.

[#components]
== Компоненты модуля

.Модуль состоит из следующих компонентов:
.. Компонент инсталлятора 1
.. Компонент инсталлятора 2
.. Справочник {nss}
.. Справочник {ne}
.. Библиотеки API модуля.

[#purpose-function]
== Назначение и функции модуля

Администратор системы создает карточку с настройками уведомления: тему и текст уведомления, получателей, канал. Также администратор создает карточку рассылки, в которой выбирает из _Справочника {ne}_ конкретное событие, вызывающее рассылку уведомлений и карточки с настройками уведомления.

Событие отправляет запрос с идентификатором корневого типа события и список объектов в карточку сообщений сервиса обработки запросов на формирование уведомлений.
Служба {ws} обнаруживает новое сообщение в карточке сообщений и передает его сервису на обработку.

После обработки формируются экземпляры уведомления на отправку, которые попадают в очередь на обработку для нужного канала отправки уведомлений.
Канал отправки уведомлений определяет адресатов уведомлений, формирует сообщение по заданной модели, прикладывает вложения и отправляет уведомление.

[#outer-links]
== Сведения о связях с другими системами

_{ns}_ является сервисом рассылки уведомлений в системе {dv}.

Модуль предоставляет публичные интерфейсы, которые используются системой {dv} для вызова функций по работе с уведомлениями.

[#doc-list]
== Разделы документации

.Документация модуля содержит следующие разделы:
. Общие сведения о модуле.
. Администрирование модуля.
