= Общие сведения о модуле

{ns} предназначен для формирования и рассылки уведомлений, представляет собой набор расширений Службы {ws}. Модуль отслеживает изменения в карточках, требующие уведомления. При получении запроса, сервис формирует соответствующее обращение в {wc}. После выполнения запроса модуль отправляет уведомление соответствующим образом.

[#components]
== Компоненты модуля

.Модуль состоит из следующих компонентов:
.. Расширение {wc}а -- компоненты, необходимые для работы {wc}а.
.. Расширение службы {ws} -- компоненты, открывающие возможность работы с функциями модуля _{ws}_.
.. Справочник {nss} -- содержит информацию обо всех функциональных компонентах, которые могут быть использованы для формирования, обработки и отправки уведомлений.
.. Справочник {ne} -- содержит информацию о событиях, на которые может быть подписана рассылка уведомлений.
.. Карточка настроек рассылки уведомления -- связывает событие и шаблоны для формирования уведомлений. Для периодического события также определяет компонент, формирующий контекст данных.
.. Карточка настроек уведомления -- шаблон для формирования уведомлений. Хранит все ссылки на компоненты и их настройки, которые используются для формирования экземпляров уведомлений из контекста данных и передачи их по каналу отправки.
.. Библиотеки API модуля.

[#purpose-function]
== Назначение и функции модуля

Администратор системы создает карточку с настройками уведомления: тему и текст уведомления, получателей, канал. Также администратор создает карточку рассылки, в которой выбирает из _Справочника {ne}_ конкретное событие, вызывающее рассылку уведомлений и карточки с настройками уведомления.

Событие отправляет запрос с идентификатором корневого типа события и список объектов в карточку сообщений сервиса обработки запросов на формирование уведомлений.
Служба {ws} обнаруживает новое сообщение в карточке сообщений и передает его сервису на обработку.

После обработки формируются экземпляры уведомления на отправку, которые попадают в очередь на обработку для нужного канала отправки уведомлений.
Канал отправки уведомлений определяет адресатов уведомлений, формирует сообщение по заданной модели, прикладывает вложения и отправляет уведомление.

[#outer-links]
== Сведения о связях с другими системами

_{ns}_ является сервисом рассылки уведомлений в системе {dv}.

Модуль предоставляет публичные интерфейсы, которые используются системой {dv} для вызова функций по работе с уведомлениями.

[#terms]
== Основные понятия

* _Источник уведомления_ -- информационный объект, создающий запрос на создание уведомления.
* _Запрос на формирование уведомлений_ -- позволяет сохранить и далее обработать определённый факт необходимости формирования уведомления.
* _Контекст данных уведомления_ -- информационный объект, относительно которого формируется уведомление. На основе данных этого объекта может быть построена модель данных, на базе которой с применением шаблона будет сформирован и отправлен экземпляр уведомления.
* _Шаблон уведомления_ -- позволяет настроить правила преобразования контекста данных уведомления в экземпляр уведомления.
* _Экземпляр уведомления_ -- сформированное уведомление, готовое к отправке через определённый канал уведомлений.
* _Канал отправки уведомления_ -- позволяет на основе очереди сформированных экземпляров уведомлений транслировать получателей уведомления заданных в терминах записей справочников {dv} в адресатов в системе отправки\получения уведомлений и осуществить отправку уведомлений этим адресатам.

[#doc-list]
== Разделы документации

.Документация модуля содержит следующие разделы:
. Общие сведения о модуле.
. Администрирование модуля.
