= Структура модуля

{ns} содержит в себе бизнес-логику: операции регистрации, отзыва и проверки статуса.

[#components]
== Компоненты модуля

.Модуль состоит из следующих компонентов:
.. Расширение для Службы {ws} -- _{ns}_.
.. Серверное расширение {wc}а, сигнализирующее модулю о необходимости зарегистрировать уведомление.
.. Карточка настроек уведомления.
.. Карточка настроек рассылки уведомлений.
.. Справочник {nss}.
.. Справочник событий уведомлений.

[#settings-directory]
=== Справочник {nss}

Справочник предназначен для хранения следующих настроек в карточках настроек уведомлений:

* Настройки компонент контекста данных уведомлений.
* Настройки компонент формирования уведомления.
* Настройки каналов отправки уведомлений.
* Настройки компонент обработки ответа на уведомление (опционально).

Справочник поставляется в составе модуля _{ns}_.

[#events-directory]
=== Справочник событий уведомлений

Когда возникает определенное событие, например, завершается задание на согласование, требуется отправка уведомлений по нему. В карточке настроек уведомления имеется возможность настроить то, какие уведомления рассылать, кому, куда.

Справочник можно заполнять через интерфейс, при помощи кода расширений сервиса уведомлений или с использованием DVExplorer.

[#sett-card]
=== Карточка настроек уведомления

В карточке настроек уведомления указывается следующая информация:

* Название карточки.
* Описание карточки.
* Тему уведомления.
//  (позже сделаем поддержку XSLT-преобразований):
* Текст уведомления.
// (позже сделаем поддержку XSLT-преобразований):
* Получателей уведомления из справочника сотрудников.
// (позже сделаем поддержку XSLT-преобразований).
Среди получателей могут быть выбраны сотрудники, организации/подразделения, роли, группы, контрагенты.

* Канал уведомления из списка полученного из <<settings-directory,Справочника настроек>> сервиса уведомлений.
// , в начале будет доступен только вариант с электронной почтой:
* Какие вложения прикреплять к уведомлению.
* Основные файлы.
* Дополнительные файлы.

[#sending-card]
=== Карточка настроек рассылки уведомлений

В карточке настроек рассылки уведомлений указывается:

* Название карточки.
* Событие из справочника событий.
* Ссылки на созданные карточки настроек уведомления.

[#inner-links]
== Сведения о связях между составными частями модуля

Модуль отслеживает изменения в карточках, требующие уведомления. При получении запроса, сервис формирует соответствующее обращение в {wc}. После выполнения запроса модуль отправляет уведомление соответствующим образом.
