= Вспомогательные модули

Обычно обработкой стандартных событий в карточках Заданий занимается Служба диспетчера событий, но можно переназначить её на вспомогательный модуль, регистрирующий события для Сервиса уведомлений вместо стандартных действий.

NSTaskMessagesService::
Вспомогательный модуль, переопределяющий обработку стандартных событий карточки _Задания_: отправка,завершение, приёмка, возврат. При наступлении этих событий генерирует сообщение в сервис регистрации событий уведомлений.
+
.Чтобы активировать вспомогательный модуль:
. Откройте в DVExplorer справочник видов для выбранного или родительского вида карточки _Задание_.
. Создайте в подсекции `Services` строку (или измените существующую) и укажите значения полей:
+
 TypeName = DocsVision.NotificationService.ObjectModel.TaskRouting.NSTaskMessagesService, DocsVision.NotificationService.ObjectModel, Version=5.5.0.0, Culture=neutral, PublicKeyToken=7148afe997f90519
+
 Disabled = False
+
. В остальных строках подсекции установите значение поля:
+
 Disabled = True
