= Компоненты контекста данных

CardXmlExportDataContext::
Не использует дополнительные настройки в Справочнике {nss}.
+
Абстрактный класс компонента контекста данных, реализующий экспорт карточки и данные справочников в формат Xml и выбор вложений из файлов смежных документов.
+
.Возвращает модель уведомления следующего наполнения:
* `Data` -- объединённый текст XML выбранных карточек со связанными данными справочников.
* `MainFiles` -- если среди объектов экспорта есть карточки типа _Документ_, то в список добавляются основные файлы этих документов; если есть карточки типа _Задание_, то проверяются карточки типа _Документ_ из списка ссылок заданий.
* `AdditionalFiles` -- если среди объектов экспорта есть карточки типа _Документ_, то в список добавляются дополнительные файлы этих документов; если есть карточки типа _Задание_, то проверяются карточки типа _Документ_ из списка ссылок заданий.

CardXmlExportWith1LevelDataContext::
Класс компонента контекста данных на базе `CardXmlExportDataContext`, выбирающий карточки со связанными до 1 уровня.

CardXmlExportWith2LevelDataContext::
Класс компонента контекста данных на базе `CardXmlExportDataContext`, выбирающий карточки со связанными до 2 уровня.

CardXmlExportWith3LevelDataContext::
Соответствует компоненту контекста данных _Экспорт XML карточки со связанными 3 уровня_.
+
Не использует дополнительные настройки в Справочнике {nss}.
Класс компонента контекста данных на базе `CardXmlExportDataContext`, выбирающий карточки со связанными до 3 уровня.

TRTaskDataContext::
Соответствует компоненту контекста данных _Экспорт заданий с завершением из почты_.
+
Не использует дополнительные настройки в Справочнике {nss}.
+
Класс компонента экспорта, строящий особую модель (`DocsVision.BackOffice.TaskRouting.Model.TaskModel`), совместимую с почтовым клиентом. Для этой модели требуется XSLT компонент с особым преобразованием для построения текста уведомления (Карточка настроек\Настройки содержания). Он также вычисляет получателей и файлы в соответствии с логикой почтового клиента.
+
Возвращает модель уведомления следующего наполнения:
`Data` - текст XML полученной модели.
`IncludedRecipients` - получатели типа Сотрудник, выбранные логикой почтового клиента.
`MainFiles` - файлы вложений, выбранные логикой почтового клиента.
