= Компоненты отправки уведомления

== MailSendComponent

Соответствует компоненту отправки "Электронная почта". Не использует дополнительные настройки в Справочнике {nss}.

Класс компонента выполняет отправку уведомления с применением `DocsVision.BackOffice.Notifications.EmailNotificationManager`. Данные уведомления преобразуются в формат, подходящий для `EmailNotificationManager`. Настройка самого `EmailNotificationManager` возможна в {of-mc}, на вкладке _Соединения\Почтовый сервер_.

Класс компонента может выбирать файлы вложений из версий, карточек файлов с версиями или документов (для документа берётся только 1 файл). Адреса получателей определяются в зависимости от их типа следующим образом:

_Подразделение_, _Группа_ или _Роль_ -- выбирает адреса всех сотрудников, входящих в данный объект.

* Сотрудник или Сотрудник контрагента -- получает значение из поля `Email`.
* Простое значение -- использует переданный текст в качестве адреса.
* Для всех собранных адресов проверяется соответствие строки общепринятому формату адреса электронной почты.

== MtsSmsSendComponent

Соответствует компоненту отправки _МТС-Маркетолог СМС_.

Требует дополнительные настройки в Справочнике {nss}.

Дополнительные настройки должны представлять XML-сериализацию объекта `DocsVision.NotificationService.ObjectModel.Extensions.SMSServiceSettings`.

Класс компонента выполняет отправку уведомления при помощи API МТС-Маркетолог. Для работы компонента требуется аккаунт доступа к API с активным пакетом SMS. Данные аккаунта и адреса доступа, а также другие настройки передаются компоненту в объекте `SMSServiceSettings`.

Класс компонента использует тело сообщения в качестве отправляемого сообщения, ограничивая его размер в соответствии с настройками. Адреса получателей определяются в зависимости от их типа следующим образом:

* Подразделение -- получает значение из поля `Phone`.
* Сотрудник или Сотрудник контрагента -- получает значение из поля `MobilePhone`.
* Простое значение -- использует переданный текст в качестве адреса.
+
Значение имеют только корректные адреса в виде 11-значного номера телефона.
