= Компоненты преобразования данных

BaseTransformComponent::
Абстрактный класс компонента преобразования данных, содержащий общую реализацию построения экземпляра уведомления. Рекомендуется использовать при разработке своих компонентов для упрощения реализации.

PlainTextComponent::
Соответствует компоненту преобразования _Простой текст_.
+
Не использует дополнительные настройки в Справочнике {nss}, требует заполнения параметра в xref:user:settings-card.adoc[карточке настроек] при применении
Возвращает текст, указанный в параметре (карточка настроек).

XsltDataTransformComponent::
Соответствует компоненту преобразования "XSLT преобразование".
+
Не использует дополнительные настройки в Справочнике {nss}, требует заполнения параметра в xref:user:settings-card.adoc[карточке настроек] при применении
+
Необходимо чтобы данные, полученные от компонента контекста данных, являлись корректным XML, а указанное значение параметра -- корректным XSLT. Данный компонент применяет преобразование (значение параметра) к XML (входные данные) и возвращает полученный текст. В частности, компонент совместим с `CardXmlExportDataContext`.
