= Журналы модуля

.Разные компоненты Сервиса отвечают за ведение разных журналов на сервере:
. Взаимодействие пользователя с карточками Сервиса осуществляется через {wc}, поэтому при проблемах взаимодействия смотрим лог {wc}а `каталог-установки-{dv}\WebClient\5.5\Logs\`.
. Основная работа Сервиса выполняется Службой {ws}. Подпроцесс Службы {ws} ведёт текстовый лог `каталог-установки-{dv}\WorkerService\5.5\Logs\%WorkerService%_NotificationService`.
. Созданные сервисом сообщения можно просматривать в очереди исходящих сообщений консоли управления, полученные -- в очереди входящих сообщений. Входящие сообщения должны быть обработаны сервисом, и могут иметь статус:
+
* Не обработано -- сообщение ожидает обработки в очереди;
* Пауза -- обработка сообщения приостановлена и не будет выполнена;
* Ошибка -- во время обработки сообщения произошла ошибка;
* Блокировка -- сообщение ожидает снятия блокировки с одной или нескольких объектов.
После обработки входящее сообщение удаляется из очереди (запись в карточке при этом сохраняется).
+
. Каналы отправки дополнительно фиксируютfootnote:[При разработке собственных каналов отправки следует реализовать журналирование посредством класса `DocsVision.BackOffice.Notifications.NotificationLogManager`.] результаты своей работы в карточках Журнала рассылки уведомлений. Просмотр журналов доступен в папке menu:Сервис уведомлений[Поиск по журналу].
