= Настройка периодичности рассылки уведомлений

. Чтобы настроить периодические уведомления:
. Установите флаг `*Периодические уведомления*` и задайте запросы для поиска карточек, по которым будут разосланы уведомления:
+
NOTE: Обратите внимание, что при установке флага `*Периодические уведомления*` поле выбора события становится недоступным.
+
** Список настроенных поисковых запросов.
** Список зарегистрированных компонентов источника данных -- (обязательное поле) для сохранения карточки обязательно должен быть выбран поисковый запрос или компонент. Можно использовать как альтернативу атрибутивному поиску.
** Список зарегистрированных компонентов постобработки (необязательное поле) -- компоненты, которые смогут обработать полученные результаты поиска, например, сгруппировать полученные задания по исполнителям.
+
. Укажите настройки расписания. Выберите периодичность отправки уведомлений при помощи взаимоисключающих переключателей групп полей "Ежедневно", "Еженедельно", "Ежемесячно":
+
** _Ежедневно_ -- в поле _Повторять каждые_ заполняется целым числом, если нужно отправлять уведомление каждый определённый день, например, Каждый `1` день, Каждый `2` день и так далее.
** _Еженедельно_ -- если требуется отправка уведомления в определенный день недели, напротив соответствующего дня необходимо установить флаг. Позволяет настроить отправку уведомления каждую определённую неделю, заполнив поле _Повторять каждые_ целым числом, например Каждую `1` неделю, Каждую `2` неделю и так далее.
** _Ежемесячно_ -- позволяет настроить отправку уведомления каждый определённый месяц. В поле _Каждого_ укажите целое число не более `12`, например, цифра `2` будет означать каждый второй месяц.
+
Если нужно отправлять уведомление каждый определённый день месяца, например, каждый первый день месяца, установите флаг в поле _Число месяца_, а в поле _Значение дня_ укажите число не более `31`.
+
Если требуется отправлять уведомление каждый определённый день выбранной недели месяца, например, каждый понедельник второй недели месяца, установите флаг в поле _День недели_, соседние поля заполняются значениями номера недели и дня недели соответственно. +
Список номеров недели представлен следующими значениями: `Перв.`, `Втор.`, `Трет.`, `Четверт.`, `Пят.`. +
Список дней недели представлен следующими значениями: `Пн.`, `Вт.`, `Ср.`, `Чт.`, `Пт.`, `Сб.`, `Вс.`.
+
NOTE: Флаг может быть установлен либо в поле _Число месяца_, либо в поле _День недели_, но не в обоих полях одновременно.
+
. Укажите настроки периодичности отправки уведомления в пределах одного дня в группе полей _Периодичность в день_. Установите флаг в одной из строк: "Время" или "Каждые", чтобы сделать соседние поля доступными для изменения:
+
** Установите флаг в строке _Время_, чтобы задать время уведомления в заданый день.
** Установите флаг в строке _Каждые_, чтобы задать периодичность уведомления. Укажите целое число, например `5`, укажите единицы времени, например `часов`. Укажите часы и минуты в полях _Время начала_ и _Время завершения_ в формате `ЧЧ:ММ`.
+
. Настройте _Продолжительность_ рассылки:
+
--
** Выберите _Дату начала_ отправки уведомления (нельзя выбрать прошедшую дату) и _Дату завершения_ из календаря.
** Если дата завершения уведомлений не определена, установите флаг `*Бесконечно*`. В таком случае поле _Дата завершения_ становится недоступным для изменения, а у уведомлений не будет даты завершения рассылки.
--
+
. Данные расписания будут записаны в _Карточку расписания_ после установки флага `*Активно*`.
+
После утановки флага редактирование распсиания становится недоступным, настройки расписания будут сохранены в связанной "Карточке настроек рассылки уведомления". Уведомления будут отправляться согласно настроенному расписанию. Если администратор удалит "Карточку настроек рассылки уведомлений", "Карточка расписания" также будет удалена.
+
