= Базовые события справочника событий

Следующие события включены в базовую версию модуля для упрощения эксплуатации.

Задание (общее уведомление)::
Используйте событие _Задание (общее уведомление)_ чтобы формировать уведомление в любой момент жизни карточки задания, если общий формат уведомления не зависит от выполненной операции, вида и состояния карточки задания. В базовой поставке это событие будет вызываться, если по карточке типа _Задание_ отправлено неопределённое событие, см. `xref:programmer:Interfaces/INotificationEventRegistrationService_IN.adoc[INotificationEventRegistrationService]`.

Задание начато::
Используйте событие _Задание начато_, чтобы сформировать уведомление о новом задании. Это событие можно зарегистрировать вручную, или настроить обработчик стандартных событий задания, чтобы регистрировать его автоматически при выполнении соответствующей операции над карточкой задания.

Задание завершено::
Используйте событие _Задание завершено_, чтобы сформировать уведомление о завершении исполнения задания. Это событие можно зарегистрировать вручную, или настроить обработчик стандартных событий задания, чтобы регистрировать его автоматически при выполнении соответствующей операции над карточкой задания.

Задание на приёмке::
Используйте событие _Задание на приёмке_, чтобы сформировать уведомление о завершении работы исполнителя с заданием и передаче его на приёмку контролирующему сотруднику. Это событие можно зарегистрировать вручную, или настроить обработчик стандартных событий задания, чтобы регистрировать его автоматически при выполнении соответствующей операции над карточкой задания.

Задание на доработке::
Используйте событие _Задание на доработке_, чтобы сформировать уведомление о возврате задания с контроля на доработку исполнителю. Это событие можно зарегистрировать вручную, или настроить обработчик стандартных событий задания, чтобы регистрировать его автоматически при выполнении соответствующей операции над карточкой задания.
