= Компоненты преобразования данных

Компоненты преобразования данных предназначены для преобразования входящих данных и получения на их основе значений для элементов уведомления:

* Тема
* Содержание
* Получатели
+
Поскольку получатель обычно представлен объектом {dv} а не простым адресом, компонент преобразования может иметь собственный механизм определения получателя из строки. Компонент пытается распознать строку как XML формат получателя, при неудаче -- как перечисление идентификаторов по которым можно найти объекты, при следующей неудаче исходная строка считается простым адресом.

Некоторые компоненты преобразования, применяемые в качестве основного в карточке настроек уведомления также могут изменять дополнительные элементы уведомления, получаемые от компонента контекста данных:

* Дополнительные получатели
* Исключенные получатели
* Основные вложения
* Дополнительные вложения

Для корректной работы используемый компонент преобразования должен быть совместим с форматом данных, возвращаемых компонентом контекста данных. Результатом работы основного компонента преобразования является модель уведомления, готовая к отправке. Однако в случае применения отдельного компонента для формирования темы, содержания или получателей будут изменён соответствующий элемент в уведомлениях, подготовленных основным компонентом.

Простой текст::
Не использует дополнительные настройки в Справочнике {nss}, требует заполнения параметра в xref:admin:settings-card.adoc[карточке настроек] при применении. Возвращает текст, указанный в параметре в карточке настроек.
+
Этот компонент не использует результат работы компонента контекста данных, поэтому его применение не ограничено.

XSL-преобразование::
Не использует дополнительные настройки в Справочнике {nss}, требует заполнения параметра в xref:admin:settings-card.adoc[карточке настроек] при применении.
+
Необходимо чтобы данные, полученные от компонента контекста данных, являлись корректным XML, а указанное значение параметра в xref:admin:settings-card.adoc[карточке настроек] -- корректного XSLT. Данный компонент применяет преобразование к XML и возвращает полученный текст. В частности, данный компонент совместим с компонентом контекста данных _Экспорт XML карточки со связанными 3 уровня_.
