= Компоненты контекста данных

Компоненты контекста данных предназначены для извлечения данных из источника уведомления и представления их в каком-либо виде, а также построения первичной модели уведомления на основании этих данных.

.Первичная модель содержит следующие элементы уведомления:
* Данные для преобразования
* Дополнительные получатели
* Исключенные получатели
* Основные вложения
* Дополнительные вложения

[#l3]
Экспорт XML карточки со связанными 3 уровня::
Не использует дополнительные настройки в Справочнике {nss}.
+
--
.Возвращает модель уведомления следующего наполнения:
* Данные для преобразования -- объединённый текст XML выбранных карточек со связанными до 3 уровня включительно и используемыми данными справочников.
* Основные вложения -- если среди объектов экспорта есть карточки типа _Документ_, то в список добавляются основные файлы этих документов; если есть карточки типа Задание, то проверяются карточки типа _Документ_ из списка ссылок заданий.
* Дополнительные вложения -- если среди объектов экспорта есть карточки типа _Документ_, то в список добавляются дополнительные файлы этих документов; если есть карточки типа _Задание_, то проверяются карточки типа _Документ_ из списка ссылок заданий.
--

[#mail]
Экспорт заданий с завершением из почты::
Не использует дополнительные настройки в Справочнике {nss}.
+
Компонент данных используется для взаимодействия с почтовым клиентом {dv}. Для построения текста уведомления (menu:Карточка настроек[Настройки содержания]) требуется компонент _XSL-преобразование_ со значением параметра, совместимым с моделью задания почтового клиента. Данный компонент также вычисляет получателей и файлы в соответствии с логикой почтового клиента, поэтому может применяться без дополнительного вычисления получателей.
+
--
.Возвращает модель уведомления следующего наполнения:
* Данные для преобразования -- текст XML модели `TaskModel`.
* Дополнительные получатели -- получатели типа _Сотрудник_, выбранные логикой почтового клиента.
* Основные вложения -- файлы вложений, выбранные логикой почтового клиента.
--
+
См. пример XML структуры модели "TaskModel" по ссылке: xref:attachment$task-model.xsl[task-model.xsl].
+
См. пример XSL-преобразования для создания письма с кнопками управления заданием по ссылке: xref:attachment$mail-buttons.xsl[mail-buttons.xsl].
